# Generated by Django 4.1.3 on 2022-12-01 08:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

'''
def create_initial_data(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    account = apps.get_model("Accounts", "AccountInfo")
    card = apps.get_model("Accounts","CardInfo")
    account1 = account.objects.create(account_number="1234567890",balance=200)
    account2 = account.objects.create(account_number="1111111111", balance=300)
    account3= account.objects.create(account_number="2222222222", balance=400)
    card1 = card.objects.create(card_number='1111222233334444',account_number=account.objects.get(pk=account1.pk),pin="1234",name='a')
    card2 = card.objects.create(card_number='2222333344445555',account_number=account.objects.get(pk=account2.pk),pin="1234",name='b')
    card3 = card.objects.create(card_number='3333444455556666',account_number=account.objects.get(pk=account3.pk),pin="1234",name='c')
def delete_initial_data(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    account = apps.get_model("Accounts", "AccountInfo")
    card = apps.get_model("Accounts","CardInfo")
    account.objects.filter(account_number="1234567890").delete()
    account.objects.filter(account_number="1111111111").delete()
    account.objects.filter(account_number="2222222222").delete()
    card.objects.filter(card_number='1111222233334444').delete()
    card.objects.filter(card_number='2222333344445555').delete()
    card.objects.filter(card_number='3333444455556666').delete()
'''
    

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(create_initial_data),
    ]

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('account_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='계좌번호')),
                ('balance', models.BigIntegerField(verbose_name='잔액')),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('name', models.CharField(max_length=35, verbose_name='이름')),
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='카드번호')),
                ('pin', models.CharField(max_length=4, verbose_name='핀번호')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('010-?[1-9]\\d{3}-?\\d{4}$')], verbose_name='전화번호')),
                ('account_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.accountinfo', verbose_name='계좌번호')),
            ],
        ),
    ]
