# Generated by Django 4.1.3 on 2022-11-30 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('account_number', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='계좌번호')),
                ('balance', models.BigIntegerField(verbose_name='잔액')),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('name', models.CharField(max_length=35, verbose_name='이름')),
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='카드번호')),
                ('pin', models.CharField(max_length=4, verbose_name='핀번호')),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('010-?[1-9]\\d{3}-?\\d{4}$')], verbose_name='전화번호')),
                ('account_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.accountinfo', verbose_name='계좌번호')),
            ],
        ),
    ]
