# Generated by Django 4.1.3 on 2022-12-01 08:58

from django.db import migrations

def create_initial_data(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    account = apps.get_model("Accounts", "AccountInfo")
    card = apps.get_model("Accounts","CardInfo")
    account.objects.create(account_number="1234567890",balance=200)
    account.objects.create(account_number="1111111111", balance=300)
    account.objects.create(account_number="2222222222", balance=400)
    card.objects.create(card_number='1111222233334444',account_number=account.objects.get(pk="1234567890"),pin="1234",name='a')
    card.objects.create(card_number='2222333344445555',account_number=account.objects.get(pk="1111111111"),pin="1234",name='b')
    card.objects.create(card_number='3333444455556666',account_number=account.objects.get(pk="2222222222"),pin="1234",name='c')
def delete_initial_data(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    account = apps.get_model("Accounts", "AccountInfo")
    card = apps.get_model("Accounts","CardInfo")
    account.objects.filter(account_number="1234567890").delete()
    account.objects.filter(account_number="1111111111").delete()
    account.objects.filter(account_number="2222222222").delete()
    card.objects.filter(card_number='1111222233334444').delete()
    card.objects.filter(card_number='2222333344445555').delete()
    card.objects.filter(card_number='3333444455556666').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
