# Generated by Django 4.1.3 on 2022-11-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_accountinfo_remove_cardinfo_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='card_number',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='카드번호'),
        ),
    ]
