# Generated by Django 4.1.3 on 2022-12-16 07:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('balance', 'balance'), ('withdraw', 'withdraw'), ('deposit', 'deposit'), ('transfer', 'transfer')], default='balance', max_length=20)),
                ('response_code', models.CharField(max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=12)),
                ('card_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.cardinfo')),
            ],
        ),
    ]
